<a href="https://colab.research.google.com/github/AykanIpek/fast-food-sales-analysis/blob/main/Data_Discovery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
menu_items = pd.read_csv('/content/drive/MyDrive/Data Science Proje 2/Fast-Food Restaurant Chain/menu_items.csv')
menuitem = pd.read_csv('/content/drive/MyDrive/Data Science Proje 2/Fast-Food Restaurant Chain/menuitem.csv')
pos_ordersale = pd.read_csv('/content/drive/MyDrive/Data Science Proje 2/Fast-Food Restaurant Chain/pos_ordersale.csv')
store_restaurant = pd.read_csv('/content/drive/MyDrive/Data Science Proje 2/Fast-Food Restaurant Chain/store_restaurant.csv')

In [ ]:
menu_items.head()

,MenuItemName,MenuItemDescription,PLU,MenuItemId,RecipeId
0,FtL/Ham,Ham FtLong,111000004,1,6
1,Six/Ham,Ham 6 inch,121000004,2,7
2,FfB/Ham,Ham FtFbd,112000004,3,2
3,fBd/Ham,Ham FlatBd,122000004,4,8
4,Sld/Ham,Ham Salad,131000004,5,9

In [ ]:
menu_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8005 entries, 0 to 8004
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   MenuItemName         8005 non-null   object
 1   MenuItemDescription  8005 non-null   object
 2   PLU                  8005 non-null   int64
 3   MenuItemId           8005 non-null   int64
 4   RecipeId             8005 non-null   int64
dtypes: int64(3), object(2)
memory usage: 312.8+ KB

In [ ]:
menuitem.head()

,MD5KEY_MENUITEM,MD5KEY_ORDERSALE,CategoryDescription,DepartmentDescription,Description,StoreNumber,TaxInclusiveAmount,TaxAmount,AdjustedPrice,DiscountAmount,Price,Quantity,PLU,Id,date
0,001E0224E4EDA63D6FED96D59E0C1E76,072D3B76BE58E4553A373AF3206D2CA5,Footlong,Footlong Sub,Chickn Strips FtLong,46673,0,0.6975,7.75,0.00,7.75,1,111000041,326,15-03-05
1,003E4E20196B2F5BDD33CE06D2943EF4,14811D4F3458058007B0B6908C2DA393,Fountain,Fountain Drink 21 oz.,21oz Fountain Drink,46673,0,0.1530,1.70,0.00,1.70,1,212000126,280,15-03-05
2,012A55E5551C95A559A7B074AE85117E,22FA6C39B7A15ABB6EB568E66A6B30E1,6 Inch,6 Inch Sub,B.M.T. 6 inch,12631,0,0.3230,3.64,0.61,4.25,1,121000008,8,15-03-05
3,01B07F1C6DC6945796571FC78735DA16,915B69612845BBD974C39AC105F5CA8C,6 Inch,6 Inch Sub,Veggie Delite 6 inch,12631,0,0.3328,3.75,0.00,3.75,1,121000001,91,15-03-05
4,02DE19974DE5304BF243A1C2EC639495,CD6386C802450EDCF13A3D112D1F86EC,Add On,Add On 6in Portion,Avocado Add6in,12631,0,0.0443,0.50,0.00,0.50,1,175000062,564,15-03-05

In [ ]:
menuitem.shape

(91431, 15)

In [ ]:
menuitem.isnull().sum()

MD5KEY_MENUITEM          0
MD5KEY_ORDERSALE         0
CategoryDescription      0
DepartmentDescription    0
Description              0
StoreNumber              0
TaxInclusiveAmount       0
TaxAmount                0
AdjustedPrice            0
DiscountAmount           0
Price                    0
Quantity                 0
PLU                      0
Id                       0
date                     0
dtype: int64

In [ ]:
menuitem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91431 entries, 0 to 91430
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   MD5KEY_MENUITEM        91431 non-null  object
 1   MD5KEY_ORDERSALE       91431 non-null  object
 2   CategoryDescription    91431 non-null  object
 3   DepartmentDescription  91431 non-null  object
 4   Description            91431 non-null  object
 5   StoreNumber            91431 non-null  int64
 6   TaxInclusiveAmount     91431 non-null  int64
 7   TaxAmount              91431 non-null  float64
 8   AdjustedPrice          91431 non-null  float64
 9   DiscountAmount         91431 non-null  float64
 10  Price                  91431 non-null  float64
 11  Quantity               91431 non-null  int64
 12  PLU                    91431 non-null  int64
 13  Id                     91431 non-null  int64
 14  date                   91431 non-null  object
dtypes: float64(4), int64(5), object(6)
memory usage: 10.5+ MB

In [ ]:
merged_data = pd.merge(menu_items,menuitem,left_on=["PLU","MenuItemId"],right_on=["PLU","Id"],how="outer")
merged_data.head()

,MenuItemName,MenuItemDescription,PLU,MenuItemId,RecipeId,MD5KEY_MENUITEM,MD5KEY_ORDERSALE,CategoryDescription,DepartmentDescription,Description,StoreNumber,TaxInclusiveAmount,TaxAmount,AdjustedPrice,DiscountAmount,Price,Quantity,Id,date
0,FtL/Veggie,Veggie Delite FtLong,111000001,90,20,2052C882B065389ADD327F8A408D1858,9B5BD672C1FBC8DC1F68DD8268050088,Footlong,Footlong Sub,Veggie Delite FtLong,12631.0,0.0,0.4881,5.50,0.00,5.50,1.0,90.0,15-03-05
1,FtL/Veggie,Veggie Delite FtLong,111000001,90,20,E31E9433BA0B9F3F502A250CC38CE4CB,EE8E4DA02CE3063E5385461E42CE20A4,Footlong,Footlong Sub,Veggie Delite FtLong,12631.0,0.0,0.4739,5.34,0.16,5.50,1.0,90.0,15-03-06
2,FtL/Veggie,Veggie Delite FtLong,111000001,90,20,7E5E74AE27F6A00BC57DDFD54E4398A4,07148B5E4801A309E120B0E82D627454,Footlong,Footlong Sub,Veggie Delite FtLong,12631.0,0.0,0.4162,4.69,0.31,5.00,1.0,90.0,15-03-07
3,FtL/Veggie,Veggie Delite FtLong,111000001,90,20,0D5FF30EA648AF5D19B778254E09AC25,09DD2117266458DFDAA5EC9AB418850F,Footlong,Footlong Sub,Veggie Delite FtLong,46673.0,0.0,0.0000,6.75,0.00,6.75,1.0,90.0,15-03-08
4,FtL/Veggie,Veggie Delite FtLong,111000001,90,20,1B36CC55FD5E3D31DA501CB56CA0F374,64D65F65FEE50C609B045E61E6A3CD94,Footlong,Footlong Sub,Veggie Delite FtLong,46673.0,0.0,0.0000,6.75,0.00,6.75,1.0,90.0,15-03-08

In [ ]:
pos_ordersale.head()

,MD5KEY_ORDERSALE,ChangeReceived,OrderNumber,TaxInclusiveAmount,TaxAmount,MealLocation,TransactionId,StoreNumber,date
0,00BCB738A1F814DB960C25012E9913DF,0.00,67,0,0.56,0,67,46673,15-03-05
1,03438C257BC2DD0037F35EC8BFC0C8E2,3.46,39,0,0.54,0,39,12631,15-03-05
2,04AEF56CF3130AC1EFAD41C470F5245D,0.00,81,0,0.69,0,79,46673,15-03-05
3,04BBFAD4E73C30EE2EC3B4E52509637C,0.00,159,0,1.16,0,159,12631,15-03-05
4,061AE382DC127057E8ADBBF869CFB361,0.00,51,0,0.00,0,51,12631,15-03-05

In [ ]:
pos_ordersale.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43228 entries, 0 to 43227
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   MD5KEY_ORDERSALE    43228 non-null  object
 1   ChangeReceived      43228 non-null  float64
 2   OrderNumber         43228 non-null  int64
 3   TaxInclusiveAmount  43228 non-null  int64
 4   TaxAmount           43228 non-null  float64
 5   MealLocation        43228 non-null  int64
 6   TransactionId       43228 non-null  int64
 7   StoreNumber         43228 non-null  int64
 8   date                43228 non-null  object
dtypes: float64(2), int64(5), object(2)
memory usage: 3.0+ MB

In [ ]:
merged_data = pd.merge(merged_data,pos_ordersale,on="MD5KEY_ORDERSALE",how="outer")
merged_data.head()

,MenuItemName,MenuItemDescription,PLU,MenuItemId,RecipeId,MD5KEY_MENUITEM,MD5KEY_ORDERSALE,CategoryDescription,DepartmentDescription,Description,...,Id,date_x,ChangeReceived,OrderNumber,TaxInclusiveAmount_y,TaxAmount_y,MealLocation,TransactionId,StoreNumber_y,date_y
0,FtL/RstChx,Rst Chicken FtLong,111000010.0,80.0,30.0,9C416C59949FFD99FFCC7060E02C0246,00040FB2079EE37A1A3347134FDA1222,Footlong,Footlong Sub,Rst Chicken FtLong,...,80.0,15-04-03,0.00,3549.0,0.0,0.54,0.0,3549.0,12631.0,15-04-03
1,FtL/VegPty,Veggie Patty FtLong,111000019.0,206.0,252.0,9ED95B86B85E6DC61447D01E8D035D7B,000487D84122ECFC7C2B0681D7847D07,Footlong,Footlong Sub,Veggie Patty FtLong,...,206.0,15-04-03,0.00,3588.0,0.0,1.27,0.0,3588.0,12631.0,15-04-03
2,Chp/Chips,Chips,311000100.0,277.0,302.0,AE80E5C1351D5609F4FA48BA7319D901,000487D84122ECFC7C2B0681D7847D07,Chips,Chips,Chips,...,277.0,15-04-03,0.00,3588.0,0.0,1.27,0.0,3588.0,12631.0,15-04-03
3,Six/Spicy,Spicy Italian 6 inch,121000002.0,70.0,42.0,9BAC6F747424C60B774C8EB40CA8C537,0006541E961609F6EA9B93AF996791FA,6 Inch,6 Inch Sub,Spicy Italian 6 inch,...,70.0,15-03-19,0.75,1294.0,0.0,0.00,1.0,1294.0,4904.0,15-03-19
4,FtL/Tuna,Tuna FtLong,111000006.0,74.0,75.0,0E10A6ECBF9A76AE0EB48C433CAA955E,0007198A6EA115A618FB1F7A47DA5A94,Footlong,Footlong Sub,Tuna FtLong,...,74.0,15-04-16,0.00,4976.0,0.0,0.54,0.0,4977.0,12631.0,15-04-16

In [ ]:
store_restaurant.head()

,STORE_ADDRESS1,STORE_ADDRESS2,DISTRIBUTION_REGION,STORE_STATE,STORE_CITY,STORE_ZIP,STORE_TYPE,STORE_LOYALTY_FLAG,STORE_NUMBER
0,Ninth Street,,Western,California,Berkeley,94710,Traditional,N,46673
1,Shattuck Sq,Shop #6,Western,California,Berkeley,94704,Traditional,Y,4904
2,Myrtle Avenue,,Northeast,New York,Ridgewood,11385,Traditional,Y,12631
3,Whitney Avenue,,Northeast,New York,Elmhurst,11373,Traditional,Y,20974

In [ ]:
merged_data = pd.merge(merged_data,store_restaurant,left_on="StoreNumber_y",right_on="STORE_NUMBER",how="outer")
merged_data.head()

,MenuItemName,MenuItemDescription,PLU,MenuItemId,RecipeId,MD5KEY_MENUITEM,MD5KEY_ORDERSALE,CategoryDescription,DepartmentDescription,Description,...,date_y,STORE_ADDRESS1,STORE_ADDRESS2,DISTRIBUTION_REGION,STORE_STATE,STORE_CITY,STORE_ZIP,STORE_TYPE,STORE_LOYALTY_FLAG,STORE_NUMBER
0,Six/Spicy,Spicy Italian 6 inch,121000002.0,70.0,42.0,9BAC6F747424C60B774C8EB40CA8C537,0006541E961609F6EA9B93AF996791FA,6 Inch,6 Inch Sub,Spicy Italian 6 inch,...,15-03-19,Shattuck Sq,Shop #6,Western,California,Berkeley,94704.0,Traditional,Y,4904.0
1,Six/Spicy,Spicy Italian 6 inch,121000002.0,70.0,42.0,27DB82D2D22FCE10CB97710DDAACED2A,000D0A5E452F08F480DC66A6D657BA0C,6 Inch,6 Inch Sub,Spicy Italian 6 inch,...,15-04-13,Shattuck Sq,Shop #6,Western,California,Berkeley,94704.0,Traditional,Y,4904.0
2,Chp/Chips,Chips,311000100.0,277.0,302.0,56ACDFA530E2667DEDC46CBEBA512341,000D0A5E452F08F480DC66A6D657BA0C,Chips,Chips,Chips,...,15-04-13,Shattuck Sq,Shop #6,Western,California,Berkeley,94704.0,Traditional,Y,4904.0
3,FtL/Tuna,Tuna FtLong,111000006.0,74.0,75.0,C4E9412B51FFBCAB75D391200740BBC0,0010FAF91914319D93F2D66538EB71CE,Footlong,Footlong Sub,Tuna FtLong,...,15-04-09,Shattuck Sq,Shop #6,Western,California,Berkeley,94704.0,Traditional,Y,4904.0
4,21oz21CDrk,21oz Fountain Drink,212000126.0,280.0,305.0,EC9EF6E10CEB1B8A7DD0F63891A1D85A,0010FAF91914319D93F2D66538EB71CE,Fountain,Fountain Drink 21 oz.,21oz Fountain Drink,...,15-04-09,Shattuck Sq,Shop #6,Western,California,Berkeley,94704.0,Traditional,Y,4904.0

In [ ]:
merged_data.columns

Index(['MenuItemName', 'MenuItemDescription', 'PLU', 'MenuItemId', 'RecipeId',
       'MD5KEY_MENUITEM', 'MD5KEY_ORDERSALE', 'CategoryDescription',
       'DepartmentDescription', 'Description', 'StoreNumber_x',
       'TaxInclusiveAmount_x', 'TaxAmount_x', 'AdjustedPrice',
       'DiscountAmount', 'Price', 'Quantity', 'Id', 'date_x', 'ChangeReceived',
       'OrderNumber', 'TaxInclusiveAmount_y', 'TaxAmount_y', 'MealLocation',
       'TransactionId', 'StoreNumber_y', 'date_y', 'STORE_ADDRESS1',
       'STORE_ADDRESS2', 'DISTRIBUTION_REGION', 'STORE_STATE', 'STORE_CITY',
       'STORE_ZIP', 'STORE_TYPE', 'STORE_LOYALTY_FLAG', 'STORE_NUMBER'],
      dtype='object')

In [ ]:
merged_data.isnull().sum()

MenuItemName              2606
MenuItemDescription       2606
PLU                       2606
MenuItemId                2606
RecipeId                  2606
MD5KEY_MENUITEM          10329
MD5KEY_ORDERSALE          7723
CategoryDescription      10329
DepartmentDescription    10329
Description              10329
StoreNumber_x            10329
TaxInclusiveAmount_x     10329
TaxAmount_x              10329
AdjustedPrice            10329
DiscountAmount           10329
Price                    10329
Quantity                 10329
Id                       10329
date_x                   10329
ChangeReceived            7723
OrderNumber               7723
TaxInclusiveAmount_y      7723
TaxAmount_y               7723
MealLocation              7723
TransactionId             7723
StoreNumber_y             7723
date_y                    7723
STORE_ADDRESS1            7723
STORE_ADDRESS2            7723
DISTRIBUTION_REGION       7723
STORE_STATE               7723
STORE_CITY                7723
STORE_ZIP                 7723
STORE_TYPE                7723
STORE_LOYALTY_FLAG        7723
STORE_NUMBER              7723
dtype: int64

In [ ]:
merged_data.info() #shows filled data numbers

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101760 entries, 0 to 101759
Data columns (total 36 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   MenuItemName           99154 non-null  object
 1   MenuItemDescription    99154 non-null  object
 2   PLU                    99154 non-null  float64
 3   MenuItemId             99154 non-null  float64
 4   RecipeId               99154 non-null  float64
 5   MD5KEY_MENUITEM        91431 non-null  object
 6   MD5KEY_ORDERSALE       94037 non-null  object
 7   CategoryDescription    91431 non-null  object
 8   DepartmentDescription  91431 non-null  object
 9   Description            91431 non-null  object
 10  StoreNumber_x          91431 non-null  float64
 11  TaxInclusiveAmount_x   91431 non-null  float64
 12  TaxAmount_x            91431 non-null  float64
 13  AdjustedPrice          91431 non-null  float64
 14  DiscountAmount         91431 non-null  float64
 15  Price                  91431 non-null  float64
 16  Quantity               91431 non-null  float64
 17  Id                     91431 non-null  float64
 18  date_x                 91431 non-null  object
 19  ChangeReceived         94037 non-null  float64
 20  OrderNumber            94037 non-null  float64
 21  TaxInclusiveAmount_y   94037 non-null  float64
 22  TaxAmount_y            94037 non-null  float64
 23  MealLocation           94037 non-null  float64
 24  TransactionId          94037 non-null  float64
 25  StoreNumber_y          94037 non-null  float64
 26  date_y                 94037 non-null  object
 27  STORE_ADDRESS1         94037 non-null  object
 28  STORE_ADDRESS2         94037 non-null  object
 29  DISTRIBUTION_REGION    94037 non-null  object
 30  STORE_STATE            94037 non-null  object
 31  STORE_CITY             94037 non-null  object
 32  STORE_ZIP              94037 non-null  float64
 33  STORE_TYPE             94037 non-null  object
 34  STORE_LOYALTY_FLAG     94037 non-null  object
 35  STORE_NUMBER           94037 non-null  float64
dtypes: float64(20), object(16)
memory usage: 27.9+ MB

In [ ]:
missing_summary = pd.DataFrame({
    "NaN_count" : merged_data.isnull().sum(),
    "Filled_count" : merged_data.notnull().sum(),
    "Total" : len(merged_data)
})
print(missing_summary)

                       NaN_count  Filled_count   Total
MenuItemName                2606         99154  101760
MenuItemDescription         2606         99154  101760
PLU                         2606         99154  101760
MenuItemId                  2606         99154  101760
RecipeId                    2606         99154  101760
MD5KEY_MENUITEM            10329         91431  101760
MD5KEY_ORDERSALE            7723         94037  101760
CategoryDescription        10329         91431  101760
DepartmentDescription      10329         91431  101760
Description                10329         91431  101760
StoreNumber_x              10329         91431  101760
TaxInclusiveAmount_x       10329         91431  101760
TaxAmount_x                10329         91431  101760
AdjustedPrice              10329         91431  101760
DiscountAmount             10329         91431  101760
Price                      10329         91431  101760
Quantity                   10329         91431  101760
Id                         10329         91431  101760
date_x                     10329         91431  101760
ChangeReceived              7723         94037  101760
OrderNumber                 7723         94037  101760
TaxInclusiveAmount_y        7723         94037  101760
TaxAmount_y                 7723         94037  101760
MealLocation                7723         94037  101760
TransactionId               7723         94037  101760
StoreNumber_y               7723         94037  101760
date_y                      7723         94037  101760
STORE_ADDRESS1              7723         94037  101760
STORE_ADDRESS2              7723         94037  101760
DISTRIBUTION_REGION         7723         94037  101760
STORE_STATE                 7723         94037  101760
STORE_CITY                  7723         94037  101760
STORE_ZIP                   7723         94037  101760
STORE_TYPE                  7723         94037  101760
STORE_LOYALTY_FLAG          7723         94037  101760
STORE_NUMBER                7723         94037  101760

In [ ]:
merged_data.describe()

,PLU,MenuItemId,RecipeId,StoreNumber_x,TaxInclusiveAmount_x,TaxAmount_x,AdjustedPrice,DiscountAmount,Price,Quantity,Id,ChangeReceived,OrderNumber,TaxInclusiveAmount_y,TaxAmount_y,MealLocation,TransactionId,StoreNumber_y,STORE_ZIP,STORE_NUMBER
count,9.915400e+04,99154.000000,99154.000000,91431.000000,91431.0,91431.000000,91431.000000,91431.000000,91431.000000,91431.000000,91431.000000,94037.000000,94037.000000,94037.0,94037.000000,94037.000000,94037.000000,94037.000000,94037.000000,94037.000000
mean,1.868241e+08,696.913831,648.924794,18152.995319,0.0,0.263194,3.464881,0.200753,3.473435,1.092102,371.846048,2.784176,5964.903623,0.0,0.738568,0.162319,5965.076481,18038.359795,54353.198932,18038.359795
std,7.998979e+07,1720.256694,1491.137113,14823.097615,0.0,0.291208,3.511239,0.672092,2.444280,0.534937,1078.178157,8.495380,3955.608695,0.0,0.739767,0.368745,3955.724652,14790.768827,41642.669079,14790.768827
min,1.110000e+08,1.000000,2.000000,4904.000000,0.0,0.000000,0.000000,-0.750000,0.000000,1.000000,1.000000,0.000000,1.000000,0.0,0.000000,0.000000,1.000000,4904.000000,11373.000000,4904.000000
25%,1.130002e+08,69.000000,65.000000,4904.000000,0.0,0.094900,1.270000,0.000000,1.500000,1.000000,64.000000,0.000000,2771.000000,0.0,0.470000,0.000000,2771.000000,4904.000000,11385.000000,4904.000000
50%,1.730000e+08,277.000000,302.000000,12631.000000,0.0,0.150700,2.100000,0.000000,2.100000,1.000000,276.000000,0.000000,5410.000000,0.0,0.640000,0.000000,5410.000000,12631.000000,94704.000000,12631.000000
75%,2.210001e+08,280.000000,305.000000,20974.000000,0.0,0.444700,5.500000,0.130000,5.500000,1.000000,280.000000,2.370000,8444.000000,0.0,0.930000,0.000000,8445.000000,20974.000000,94704.000000,20974.000000
max,8.110008e+08,10571.000000,9315.000000,46673.000000,0.0,43.031200,506.250000,29.250000,60.000000,75.000000,10067.000000,727.680000,16159.000000,0.0,43.230000,1.000000,16159.000000,46673.000000,94710.000000,46673.000000

In [ ]:
merged_data.shape

(101760, 36)

In [ ]:
merged_data["date_x"] = pd.to_datetime(merged_data["date_x"],format="%y-%m-%d")

In [ ]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101760 entries, 0 to 101759
Data columns (total 36 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   MenuItemName           99154 non-null  object
 1   MenuItemDescription    99154 non-null  object
 2   PLU                    99154 non-null  float64
 3   MenuItemId             99154 non-null  float64
 4   RecipeId               99154 non-null  float64
 5   MD5KEY_MENUITEM        91431 non-null  object
 6   MD5KEY_ORDERSALE       94037 non-null  object
 7   CategoryDescription    91431 non-null  object
 8   DepartmentDescription  91431 non-null  object
 9   Description            91431 non-null  object
 10  StoreNumber_x          91431 non-null  float64
 11  TaxInclusiveAmount_x   91431 non-null  float64
 12  TaxAmount_x            91431 non-null  float64
 13  AdjustedPrice          91431 non-null  float64
 14  DiscountAmount         91431 non-null  float64
 15  Price                  91431 non-null  float64
 16  Quantity               91431 non-null  float64
 17  Id                     91431 non-null  float64
 18  date_x                 91431 non-null  datetime64[ns]
 19  ChangeReceived         94037 non-null  float64
 20  OrderNumber            94037 non-null  float64
 21  TaxInclusiveAmount_y   94037 non-null  float64
 22  TaxAmount_y            94037 non-null  float64
 23  MealLocation           94037 non-null  float64
 24  TransactionId          94037 non-null  float64
 25  StoreNumber_y          94037 non-null  float64
 26  date_y                 94037 non-null  object
 27  STORE_ADDRESS1         94037 non-null  object
 28  STORE_ADDRESS2         94037 non-null  object
 29  DISTRIBUTION_REGION    94037 non-null  object
 30  STORE_STATE            94037 non-null  object
 31  STORE_CITY             94037 non-null  object
 32  STORE_ZIP              94037 non-null  float64
 33  STORE_TYPE             94037 non-null  object
 34  STORE_LOYALTY_FLAG     94037 non-null  object
 35  STORE_NUMBER           94037 non-null  float64
dtypes: datetime64[ns](1), float64(20), object(15)
memory usage: 27.9+ MB

In [ ]:
merged_data["date_x"] = merged_data["date_x"].dt.year

In [ ]:
print("max year {}, min year{}".format(merged_data.date_x.max(),merged_data.date_x.min()))

max year 2015.0, min year2015.0

In [ ]:
merged_data["date_x"] = merged_data["date_x"].fillna(0).astype(int)
merged_data["date_x"].unique()

array([2015,    0])